app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin, confirm_login
from . import login_manager
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    pass_secure = db.Column(db.String(255))

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), index=True)
    email = db.Column(db.String(255), unique=True, index=True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    # role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    pitches = db.relationship('Pitches', backref='user', lazy="dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)

    def __repr__(self):
        return f'User {self.username}'


class Pitches(db.Model):

    __tablename__ = 'pitches'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String)
    category = db.Column(db.String)
    pitch = db.Column(db.String)
    posted = db.Column(db.DateTime, default=datetime.utcnow())
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    comments_id = db.relationship(
        'Comments', backref='commenter', lazy='dynamic')
    votes = db.relationship('Votes', backref='voter', lazy="dynamic")
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'))

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls, id):
        pitches = Pitches.query.filter_by(user_id=id).all()
        return pitches


class Comments(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String(255))
    date_posted = db.Column(db.DateTime, default=datetime.utcnow())
    pitch_id = db.Column(db.Integer, db.ForeignKey('pitches.id'))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls, id):
        comments = Comments.query.filter_by(pitch_id=id).all()
        return comments


class Category(db.Model):
    __tablename__ = 'category'

    id = db.Column(db.Integer, primary_key=True)
    category = db.Column(db.String(255))

    pitch_id = db.relationship('Pitches', backref='categories', lazy='dynamic')


class Votes(db.Model):

    __tablename__ = 'votes'

    id = db.Column(db.Integer, primary_key=True)
    votes = db.Column(db.Integer)
    pitch_id = db.Column(db.Integer, db.ForeignKey('pitches.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

app/main/forms.py
from unicodedata import category
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField
from wtforms.validators import InputRequired


class PitchForm(FlaskForm):

    title = StringField('Pitch Title', validators=[InputRequired()])
    category = SelectField('Which category?', choices=[(
        1, 'Pickup'), (2, 'Products'), (3, 'Business')], validators=[InputRequired()])
    pitch = TextAreaField('Write your pitch', validators=[InputRequired()])
    submit = SubmitField('Post')


class CommentsForm(FlaskForm):
    comment = TextAreaField('Write your comment')
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import config_options
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail
import os

photos = UploadSet('photos', IMAGES)
mail = Mail()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

db = SQLAlchemy()


def create_app(config_name):
    app = Flask(__name__)
    app.config['UPLOADED_PHOTOS_DEST'] = os.getcwd()

    # configure UploadSet
    configure_uploads(app, photos)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')

    # Initializing
    login_manager.init_app(app)
    db.init_app(app)
    bootstrap = Bootstrap(app)
    mail.init_app(app)

    return app

app/main/__init__.py
from . import views
from flask import Blueprint
main = Blueprint('main', __name__)

app/main/views.py
from unicodedata import category
from flask import render_template, request, redirect, url_for, abort, jsonify
from . import main
from ..models import Category, User
from app.auth.forms import UpdateProfile
from .. import db, photos
from flask_login import login_required, current_user
from ..models import Pitches, Comments
from .forms import PitchForm, CommentsForm
from multiprocessing import Value

counter = Value('i', 0)


@main.route('/', methods=['GET', 'POST'])
def index():
    pitches = Pitches.query.all()
    title = 'Home Page'
    with counter.get_lock():
        counter.value += 1
        # save the value ASAP rather than passing to jsonify
        # to keep lock time short
        unique_count = counter.value
        counts = jsonify(count=unique_count)

    return render_template('index.html', title=title, pitches=pitches, count=counts)


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username=uname).first()
    pitches = Pitches.get_pitches(user.id)

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user=user, pitches=pitches)


@main.route('/user/<uname>/update', methods=['GET', 'POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username=uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', uname=user.username))

    return render_template('profile/update.html', form=form)


@main.route('/user/<uname>/update/pic', methods=['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username=uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile', uname=uname))


@main.route('/pitch', methods=['GET', 'POST'])
@login_required
def new_pitch():
    form = PitchForm()
    user = User.query.first()

    if form.validate_on_submit():
        pitch_title = form.title.data
        category = form.category.data
        pitch = form.pitch.data
        pitch_category = Category.query.filter_by(id=category).first()
        new_pitch = Pitches(title=pitch_title,
                            category=category, pitch=pitch, user=current_user, categories=pitch_category)
        new_pitch.save_pitch()
        return redirect(url_for('.profile', uname=user.username))

    title = 'Add Pitch'
    return render_template('new_pitch.html', title=title, pitch_form=form)


@main.route('/user/comment/<int:id>', methods=["GET", "POST"])
@login_required
def comment(id):
    form = CommentsForm()
    comments = Comments.query.filter_by(pitch_id=id).all()
    pitch = Pitches.query.filter_by(id=id).first()

    if form.validate_on_submit():
        comment_submitted = form.comment.data
        new_comment = Comments(comment=comment_submitted, commenter=pitch)
        new_comment.save_comment()

    return render_template('comments.html', comment_form=form, comments=comments, pitch=pitch)


@main.route('/category/<int:id>')
def category(id):
    pitches = Pitches.query.filter_by(category_id=id).all()

    return render_template('category.html', categories=pitches)

app/templates/base.html
{% extends 'bootstrap/base.html'%} {% block styles%} {{ super() }}
<link
  rel="stylesheet"
  href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
  integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
  crossorigin="anonymous"
/>
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  href="https://fonts.googleapis.com/css2?family=Lobster&display=swap"
  rel="stylesheet"
/>
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
  crossorigin="anonymous"
/>
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}" />
{% endblock %}

<!-- Navbar block  -->
{% block navbar %} {% include 'navbar.html' %} {% endblock %}

app/templates/category.html
{%extends 'base.html'%} {% block content %} {%if categories%} {%for category in
categories%}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div
        class="card mb-5"
        style="box-shadow: 5px 5px 5px 5px rgba(137, 43, 226, 0.157)"
      >
        <div
          class="card-title text-center"
          style="box-shadow: 5px 5px blueviolet"
        >
          <h4><i>{{category.title}}</i></h4>
        </div>
        <div class="card-body">
          <i
            class="fas fa-thumbs-up me-5"
            style="color: blueviolet"
            onclick="{{'count'}}"
          >
          </i
          ><i class="fas fa-thumbs-down" style="color: blueviolet"> [0]</i>
        </div>
        <div class="card-footer">
          <p class="fw-bolder">
            {{current_user.username}} posted on
            {{category.posted.strftime('%Y-%m-%d')}}
          </p>
          <a href="">add a comment</a>
        </div>
      </div>
    </div>
  </div>
</div>

{%endfor%} {%else%}
<h2 class="text-center">None yet</h2>

{%endif%}
<button
  class="border btn position-absolute start-50 end-50 mt-5 p-3 mb-5"
  style="background-color: rgba(137, 43, 226, 0.267)"
>
  <a class="ratings text-dark fw-bolder" href="/pitch"> ADD PITCH</a>
</button>

{%endblock%}

app/templates/comments.html
{% extends 'base.html' %} {% import "bootstrap/wtf.html" as wtf %} {% block
content%}
<div class="container">
  <div class="col-md-8 mt-3">{{ wtf.quick_form(comment_form) }}</div>
</div>
<h1 class="text-center">{{pitch.pitch}}</h1>
{% if comments %} {% for comment in comments %}
<div
  class="card"
  style="
    width: 70%;
    height: 50px;
    border-left: none;
    border-right: none;
    margin: auto;
    background-color: #cfdbd5;
  "
>
  <div class="card-body">
    <p style="font-weight: 600">{{comment.comment}}</p>
  </div>
</div>
{% endfor %} {% endif %} {% endblock %}

app/templates/index.html
{%extends 'base.html'%} {%block content%}
<h2 class="text-center">Pitches</h2>
{%if pitches%} {%for pitch in pitches%}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div
        class="card mb-5"
        style="box-shadow: 5px 5px 5px 5px rgba(137, 43, 226, 0.157)"
      >
        <div
          class="card-title text-center"
          style="box-shadow: 5px 5px blueviolet"
        >
          <h4><i>{{pitch.title}}</i></h4>
        </div>
        <div class="card-body">
          <p>Category : {{pitch.category}}</p>
          <p>{{pitch.pitch}}</p>
          <i
            class="fas fa-thumbs-up me-5"
            style="color: blueviolet"
            onclick="{{'count'}}"
          >
          </i
          ><i class="fas fa-thumbs-down" style="color: blueviolet"> [0]</i>
        </div>
        <div class="card-footer">
          <p class="fw-bolder">
            {{current_user.username}} posted on
            {{pitch.posted.strftime('%Y-%m-%d')}}
          </p>
          <a href="{{url_for('main.comment',id=pitch.id)}}">add a comment</a>
        </div>
      </div>
    </div>
  </div>
</div>
{%endfor%} {%endif%}
<button
  class="border btn position-absolute start-50 end-50 mt-5 p-3 mb-5"
  style="background-color: rgba(137, 43, 226, 0.267)"
>
  <a class="ratings text-dark fw-bolder" href="/pitch"> ADD PITCH</a>
</button>

{%endblock%}

app/templates/navbar.html
<nav>
  <div
    class="navbar navbar-light sticky-top shadow p-3 mb-5 bg-body rounded"
    style="background-color: #e3f2fd"
  >
    <i
      class="position-absolute start-0 ms-3 fas fa-feather"
      style="color: blueviolet; font-size: 150%"
    ></i>
    <h3
      class="position-absolute start-0 ms-5 mt-1"
      style="font-family: 'Lobster', cursive"
    >
      MINUTE PITCHES
    </h3>
    <div class="d-flex justify-content-center">
      <h5 class="m-3"><a class="text-dark" href="/">Home</a></h5>
      <h5 class="m-3"><a class="text-dark" href="/category/1">Pickup</a></h5>
      <h5 class="m-3"><a class="text-dark" href="/category/2">Products</a></h5>
      <h5 class="m-3"><a class="text-dark" href="/category/3">Business</a></h5>
    </div>
    {% if current_user.is_authenticated %}

    <a href="{{url_for('main.profile',uname=current_user.username)}}"
      >{{current_user.username}}</a
    >
    <button
      class="border rounded-pill btn position-absolute end-0 ms-5"
      style="background-color: blueviolet"
    >
      <a class="text-light" href="{{url_for('auth.logout')}}">Sign out</a>
    </button>
    {% else %}
    <button
      class="border rounded-pill btn position-absolute end-0 ms-5"
      style="background-color: blueviolet"
    >
      <a class="text-light" href="{{url_for('auth.login')}}">Sign in</a>
    </button>
    {%endif%}
  </div>
</nav>

app/templates/new_pitch.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block
content %}
<div class="container">
  <div class="col-md-4">{{ wtf.quick_form(pitch_form) }}</div>
</div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%} {% block content %}
<div class="container">
  <div class="row">
    <!-- displaying  Username-->
    <div class="col-md-4">
      <h3>{{user.username| capitalize}}</h3>

      <!--Displaying user bio-->
      {% if user.bio %}
      <p>{{user.bio}}</p>
      {%else%}
      <p>{{user.username| capitalize}} has no bio</p>
      {% endif %}
    </div>

    <!--Display profile photo-->
    <div class="col-md-4">
      {% if user.profile_pic_path %}

      <img
        src="{{url_for('static',filename=user.profile_pic_path)}}"
        alt=""
        class="img-thumbnail"
      />

      {%else%}
      <p>No profile picture</p>

      {% endif %} {% if user == current_user %}
      <form
        action="{{url_for('main.update_pic',uname=user.username)}}"
        method="post"
        enctype="multipart/form-data"
      >
        <input type="file" name="photos" class="form-control" required />
        <input type="submit" />
      </form>
      {%if pitches%} {%for pitch in pitches%}
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="card mb-5">
              <div
                class="card-title text-center"
                style="box-shadow: 5px 5px blueviolet"
              >
                <h4><i>{{pitch.title}}</i></h4>
              </div>
              <div class="card-body">
                <p>Category : {{pitch.category}}</p>
                <p>{{pitch.pitch}}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      {%endfor%} {%endif%} {% endif %}
    </div>
  </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %} {% block
content %}
<div class="container">{{wtf.quick_form(form)}}</div>
{% endblock %}